import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  initPoseidon2,
  poseidon2HashFixed,
  fieldToHex,
  fieldFromHex,
  icdToField,
  stringToField,
  computePolicyLeaf,
  computeDoctorSecret,
  computeDoctorLeaf,
  computeClaimHash,
  pedersenCommit,
} from "./lib/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const ARTIFACTS = join(ROOT, "scripts", "artifacts");
const SEED = join(ROOT, "scripts", "seed");
const OUT = join(ROOT, "circuits", "test_fixtures", "src", "lib.nr");

function f(v: bigint): string {
  return fieldToHex(v);
}

function nrField(name: string, hex: string): string {
  return `pub global ${name}: Field = ${hex};`;
}

function nrU64(name: string, v: number): string {
  return `pub global ${name}: u64 = ${v};`;
}

function nrBool(name: string, v: boolean): string {
  return `pub global ${name}: bool = ${v};`;
}

function nrU64Toml(name: string, v: number): string {
  return `${name} = "${v}"`;
}

function nrBoolToml(name: string, v: boolean): string {
  return `${name} = "${v}"`;
}

function nrPath(name: string, path: string[]): string {
  const elems = path.map((p) => `${p}`).join(", ");
  return `pub global ${name}: [Field; 10] = [${elems}];`;
}

async function main() {
  const policyPath = join(ARTIFACTS, "policy_tree.json");
  const aspPath = join(ARTIFACTS, "asp_tree.json");
  if (!existsSync(policyPath) || !existsSync(aspPath)) {
    console.error("Run npm run build:trees first.");
    process.exit(1);
  }

  const demo = JSON.parse(readFileSync(join(SEED, "demo_claim.json"), "utf8"));
  const policyTree = JSON.parse(readFileSync(policyPath, "utf8")) as {
    root: string;
    leaves: Array<{
      icd_code: string;
      icd_code_field: string;
      index: number;
      merkle_path: string[];
    }>;
  };
  const aspTree = JSON.parse(readFileSync(aspPath, "utf8")) as {
    root: string;
    doctors: Array<{
      license_id: string;
      doctor_secret: string;
      doctor_commitment: string;
      index: number;
      merkle_path: string[];
    }>;
  };

  await initPoseidon2();

  const j189 = policyTree.leaves.find((l) => l.icd_code === "J18.9");
  if (!j189) throw new Error("J18.9 not in policy tree");

  const md001 = aspTree.doctors.find((d) => d.license_id === "MD-001");
  if (!md001) throw new Error("MD-001 not in ASP tree");

  const policySecret = fieldFromHex(demo.policy_secret);
  const icdField = icdToField(j189.icd_code);
  const policyCommitment = await poseidon2HashFixed([icdField, policySecret]);
  const claimHash = await computeClaimHash({
    visitDate: demo.visit_date,
    policyId: demo.policy_id,
    nonce: fieldFromHex(demo.nonce),
  });

  const floor = demo.demo_a.policy_floor_cents;
  const ceiling = demo.demo_a.policy_ceiling_cents;
  const boundsHash = await poseidon2HashFixed([
    BigInt(floor),
    BigInt(ceiling),
  ]);
  const blindingA = fieldFromHex(demo.demo_a.blinding_factor);
  const amountCommitA = await pedersenCommit(
    BigInt(demo.demo_a.raw_amount_cents),
    blindingA,
  );

  const doctorSecret = fieldFromHex(md001.doctor_secret);
  const attestationHash = await poseidon2HashFixed([doctorSecret, claimHash]);

  const blindingB = fieldFromHex(demo.demo_b.blinding_factor);
  const prevSecretB = BigInt(demo.demo_b.prev_accumulator_secret);
  const newAmountB = BigInt(demo.demo_b.new_amount_cents);
  const prevCommitB = await poseidon2HashFixed([prevSecretB]);
  const newCommitB = await poseidon2HashFixed([
    prevSecretB,
    newAmountB,
    blindingB,
  ]);
  const amountCommitB = await pedersenCommit(newAmountB, blindingB);
  const deductibleMetB =
    prevSecretB + newAmountB >= BigInt(demo.demo_b.deductible_limit_cents);

  const blindingBelow = fieldFromHex(demo.demo_b_below_threshold.blinding_factor);
  const prevBelow = BigInt(demo.demo_b_below_threshold.prev_accumulator_secret);
  const newBelow = BigInt(demo.demo_b_below_threshold.new_amount_cents);
  const prevCommitBelow = await poseidon2HashFixed([prevBelow]);
  const newCommitBelow = await poseidon2HashFixed([
    prevBelow,
    newBelow,
    blindingBelow,
  ]);
  const amountCommitBelow = await pedersenCommit(newBelow, blindingBelow);
  const deductibleMetBelow =
    prevBelow + newBelow >=
    BigInt(demo.demo_b_below_threshold.deductible_limit_cents);

  const lines = [
    "// AUTO-GENERATED by scripts/generate_circuit_vectors.ts - do not edit manually.",
    "// Run: npm run generate:circuit-vectors",
    "",
    "// --- Policy validity (Demo A / J18.9) ---",
    nrField("ICD_CODE", f(icdField)),
    nrU64("ICD_LEAF_INDEX", j189.index),
    nrPath("ICD_MERKLE_PATH", j189.merkle_path),
    nrField("POLICY_SECRET", f(policySecret)),
    nrField("COVERAGE_MERKLE_ROOT", policyTree.root),
    nrField("POLICY_COMMITMENT", f(policyCommitment)),
    nrField("CLAIM_HASH", f(claimHash)),
    "",
    "// --- Amount range (Demo A) ---",
    nrU64("RAW_AMOUNT_A", demo.demo_a.raw_amount_cents),
    nrField("BLINDING_A", f(blindingA)),
    nrU64("POLICY_FLOOR", floor),
    nrU64("POLICY_CEILING", ceiling),
    nrField("AMOUNT_COMMITMENT_A", f(amountCommitA)),
    nrField("POLICY_BOUNDS_HASH", f(boundsHash)),
    "",
    "// --- Doctor attestation (MD-001) ---",
    nrField("DOCTOR_SECRET", f(doctorSecret)),
    nrU64("DOCTOR_LEAF_INDEX", md001.index),
    nrPath("ASP_MERKLE_PATH", md001.merkle_path),
    nrField("ASP_MERKLE_ROOT", aspTree.root),
    nrField("DOCTOR_COMMITMENT", md001.doctor_commitment),
    nrField("ATTESTATION_HASH", f(attestationHash)),
    nrField("CLAIM_DATA_SECRET", f(stringToField("unused"))),
    "",
    "// --- Deductible accumulator (Demo B crossing) ---",
    nrField("PREV_ACCUM_SECRET_B", f(prevSecretB)),
    nrU64("NEW_AMOUNT_B", demo.demo_b.new_amount_cents),
    nrField("NEW_AMOUNT_BLINDING_B", f(blindingB)),
    nrU64("DEDUCTIBLE_LIMIT", demo.demo_b.deductible_limit_cents),
    nrField("PREV_ACCUM_COMMIT_B", f(prevCommitB)),
    nrField("NEW_ACCUM_COMMIT_B", f(newCommitB)),
    nrField("NEW_AMOUNT_COMMIT_B", f(amountCommitB)),
    nrBool("DEDUCTIBLE_MET_B", deductibleMetB),
    "",
    "// --- Deductible below threshold ---",
    nrField("PREV_ACCUM_SECRET_BELOW", f(prevBelow)),
    nrU64("NEW_AMOUNT_BELOW", demo.demo_b_below_threshold.new_amount_cents),
    nrField("NEW_AMOUNT_BLINDING_BELOW", f(blindingBelow)),
    nrField("PREV_ACCUM_COMMIT_BELOW", f(prevCommitBelow)),
    nrField("NEW_ACCUM_COMMIT_BELOW", f(newCommitBelow)),
    nrField("NEW_AMOUNT_COMMIT_BELOW", f(amountCommitBelow)),
    nrBool("DEDUCTIBLE_MET_BELOW", deductibleMetBelow),
    "",
  ];

  writeFileSync(OUT, lines.join("\n"));
  console.log(`Wrote ${OUT}`);

  const pathArray = (path: string[]) => {
    const lines = path.map((p) => `  "${p}"`).join(",\n");
    return `[\n${lines}\n]`;
  };

  const writeToml = (path: string, content: string) => {
    writeFileSync(path, content.replace(/\r\n/g, "\n"), "utf8");
  };

  writeToml(
    join(ROOT, "circuits", "policy_validity", "Prover.toml"),
    `coverage_merkle_root = "${policyTree.root}"
policy_commitment = "${f(policyCommitment)}"
claim_hash = "${f(claimHash)}"
icd_code = "${f(icdField)}"
icd_leaf_index = ${j189.index}
icd_merkle_path = ${pathArray(j189.merkle_path)}
policy_secret = "${f(policySecret)}"
`,
  );

  writeToml(
    join(ROOT, "circuits", "amount_range", "Prover.toml"),
    `amount_commitment = "${f(amountCommitA)}"
policy_bounds_hash = "${f(boundsHash)}"
claim_hash = "${f(claimHash)}"
raw_amount = ${demo.demo_a.raw_amount_cents}
blinding_factor = "${f(blindingA)}"
policy_floor_cents = ${floor}
policy_ceiling_cents = ${ceiling}
`,
  );

  writeToml(
    join(ROOT, "circuits", "doctor_attestation", "Prover.toml"),
    `asp_merkle_root = "${aspTree.root}"
doctor_commitment = "${md001.doctor_commitment}"
claim_hash = "${f(claimHash)}"
attestation_hash = "${f(attestationHash)}"
doctor_secret = "${f(doctorSecret)}"
doctor_leaf_index = ${md001.index}
asp_merkle_path = ${pathArray(md001.merkle_path)}
claim_data_secret = "${f(stringToField("unused"))}"
`,
  );

  writeToml(
    join(ROOT, "circuits", "deductible_accumulator", "Prover.toml"),
    `prev_accumulator_commit = "${f(prevCommitB)}"
new_accumulator_commit = "${f(newCommitB)}"
new_amount_commit = "${f(amountCommitB)}"
deductible_met = ${deductibleMetB}
claim_hash = "${f(claimHash)}"
prev_accumulator_secret = "${f(prevSecretB)}"
new_amount = ${demo.demo_b.new_amount_cents}
new_amount_blinding = "${f(blindingB)}"
deductible_limit = ${demo.demo_b.deductible_limit_cents}
`,
  );

  console.log("Wrote Prover.toml for all four circuits");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
