# Circle testnet USDC — used for all settlement (not deployer-issued mock USDC)
export ZKLAIM_USDC_ISSUER="GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
export ZKLAIM_USDC_ASSET="USDC:${ZKLAIM_USDC_ISSUER}"
